name: Train in dev and prod

on:
  workflow_dispatch:

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: "AZURE DEV"
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train the model
      run: az ml job create --file src/job.yml -g rg-dp100-l31ee2fb33446402285 -w mlw-dp100-l31ee2fb33446402285 --name dev-train
    - name: Stream the training logs
      run: az ml job stream --name dev-train -g rg-dp100-l31ee2fb33446402285 -w mlw-dp100-l31ee2fb33446402285
  train-prod:
    runs-on: ubuntu-latest
    needs: train-dev
    environment: "AZURE PROD"
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train the model
      run: az ml job create --file src/job.yml -g rg-dp100-l8960dd5ad2b34e6d94 -w mlw-dp100-l8960dd5ad2b34e6d94 --name prod-train
    - name: Stream the training logs  
      run: az ml job stream --name prod-train -g rg-dp100-l8960dd5ad2b34e6d94 -w mlw-dp100-l8960dd5ad2b34e6d94
